### DISCUSSION TITLE
Header Themes

### DISCUSSION THREAD

**Discussion by giscus** [hbstack/site#521] [General]
# Header Themes

This article shows the available header themes.

https://hbstack.dev/en/modules/header/themes/

**Comment by TetraTheta** [comment]
How to apply `github.com/hbstack/header/themes/pills` theme correctly?  

I added pills theme like this:
```yaml
module:
  imports:
    # .. other imports
    - path: github.com/hbstack/header/themes/pills
```
Since I couldn't find any other theme configuration on [site](https://github.com/hbstack/site)'s config files, I didn't touched any other configuration files.

But I don't see pills theme is applied. It remains default theme.

![1](https://github.com/hbstack/site/assets/37061801/4a39a69f-6803-419a-93fe-be8c9feb0541)
