### DISCUSSION TITLE
Blog Giscus Comments Engine

### DISCUSSION THREAD

**Discussion by giscus** [hbstack/site#522] [General]
# Blog Giscus Comments Engine

This module adds support for the Giscus comments engine, which powered by GitHub Discussions.

https://hbstack.dev/en/modules/blog/comments/giscus/

**Comment by TetraTheta** [comment]
I'm not sure why Giscus doesn't get translated to my language even though it is supported by Giscus.
```yaml
# hugo.yaml
defaultContentLanguage: ko
hasCJKLanguage: true
languageCode: ko

# params.yaml
hb:
  blog:
    giscus:
      repo: 
      repo_id: [REDACTED]
      category: [REDACTED]
      category_id: [REDACTED]
      languages_mapping:
        ko: ko
        # None of these works
        #ko-KR: ko
        #ko-KR: ko-KR
        #ko-KR: ko-kr
        #ko-kr: ko
        #ko-kr: ko-KR
        #ko-kr: ko-kr
        #ko: ko
        #ko: ko-KR
        #ko: ko-kr

# languages.yaml
ko:
  languageCode: ko-KR
  languageName: 한국어
  weight: 1
```
Korean is supported language of Giscus, as `ko`. I've tried to set `params.hb.blog.giscus.languages_mapping` to `ko-kr: ko`, `ko: ko`, `ko: ko-kr`, `ko-kr: ko-kr` but none of them worked.

I don't think I mis-configured other params of Giscus because I copied values from <https://giscus.app/ko>.

When I inspect giscus script, `data-lang` was empty like `data-lang=""`. I think my configuration didn't accepted by Giscus module.

What did I have done wrong?

**Comment by razonyang** [comment]
Yep, it's a bug, didn't notice that, just fixed via https://github.com/hugomods/giscus/pull/18, please upgrade the [latest release of the module](https://github.com/hugomods/giscus/releases) to verify it.

**Reply by TetraTheta** [reply]
I can confirm that the issue was resolved with manually putting `github.com/hugomods/giscus` above `github.com/hbstack/blog/modules/giscus` like this:
```
# hugo.yaml
module:
  imports:
    - path: github.com/hugomods/giscus
    - path: github.com/hbstack/blog/modules/giscus
```
Now I see localized Giscus. Thank you for the quick bug fix!

**Comment by diogoguilhen** [comment]
im getting this error :/ any tip?

chromewebdata/:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
(index):6587 crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):6587
Refused to frame 'https://giscus.app/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

docs/:1 Unchecked runtime.lastError: The message port closed before a response was received.

**Reply by razonyang** [reply]
Hi, could you please provide an live URL for checking?

**Reply by diogoguilhen** [reply]
sure! https://productcommunity.netlify.app/

**Reply by razonyang** [reply]
Seems not available in this moment, I got ERR_NAME_NOT_RESOLVED error (redirect to https://productcommunity.com.br/pt-br/).

**Reply by diogoguilhen** [reply]
sry i just update and this take time to redirect https://productcommunity.netlify.app/pt-br/docs/

**Reply by razonyang** [reply]
The error indicates that the `pt-br` isn't support by Giscus (404), you can fallback to one of [supported languages](https://github.com/giscus/giscus/tree/main/locales) by setting the `giscus.languagesMapping`.

```
// params.yaml
giscus:
  languagesMapping:
    # the key is the site language code, the value is the Giscus supported language code.
    pt-br: pt
```

See https://github.com/giscus/giscus/blob/main/CONTRIBUTING.md#adding-localizations.
