### DISCUSSION TITLE
Docs Hooks

### DISCUSSION THREAD

**Discussion by giscus** [hbstack/site#786] [General]
# Docs Hooks

The list of docs&rsquo;s custom hooks.

https://hbstack.dev/modules/docs/hooks/

**Comment by FuadEfendi** [comment]
Hi Razon, which folder should I place `hb-docs-doc-content-end.html?` I cannot make it work

**Reply by razonyang** [reply]
Hi, to use a hook, you'll need to declare it in configuration first.

```yaml
// params.yaml
hugopress:
  modules:
    hb-custom:
      hooks:
        hb-docs-doc-content-end:
          cacheable: false
```

and then create the hook template under the **layouts/partials/hugopress/modules/hb-custom/hooks** folder.
