### DISCUSSION TITLE
Blog Hooks

### DISCUSSION THREAD

**Discussion by giscus** [hbstack/site#789] [General]
# Blog Hooks

The list of blog&rsquo;s custom hooks.

https://hbstack.dev/modules/blog/hooks/

**Comment by FuadEfendi** [comment]
Hi Razon,

I want to use custom comments (https://docs.commento.io/configuration/frontend/) - should I only have "hb-blog-post-comments" or I need some other configuration settings?

**Reply by FuadEfendi** [reply]
Maybe this, in params.yaml?
```
hugopress:
  modules:
    hb-custom:
      hooks:
        hb-blog-post-comments:
          cacheable: true
```
