### ISSUE TITLE
Parameter post_thumbnail_default not working

### ISSUE THREAD

**Issue by gavlinski** [hbstack/site#712]
https://github.com/hbstack/site/blob/575886681bb03535df7bac2e93533ec70465619a/content/modules/blog/overview/index.md?plain=1#L35

When `post_thumbnail_default: images/thumbnail.jpg` or `post_thumbnail_default: /images/thumbnail.jpg` is set in **params.yaml**, in both cases the image is found at `assets/images/` directory but it is not displayed, showing the console warning:

```
WARN  image not found: /mysite/images/thumbnail.jpg?height=360px
```

If the image is not found, then there are no errors nor warnings. But image is not displayed neither ways.

How can I make it work? Maybe remove `height=360px` parameter from somewhere?

Please tell me if you need more information for debugging.

**Comment by razonyang** [comment]
Hi, what is the full path of the parameter? It should be `hb.blog.post_thumbnail_default`. You can also check it with the real working example.

https://github.com/hbstack/site/blob/575886681bb03535df7bac2e93533ec70465619a/config/_default/params.yml#L32
https://github.com/hbstack/site/blob/main/assets/images/thumbnail.jpg

**Comment by gavlinski** [comment]
Hi, I've used [this example](https://hbstack.dev/modules/blog/overview/#site-parameters) as a reference with the same image from repository. I've tried tried several ways, but I couldn't find out why the image wasn't displayed (which warning message only appears when it is found).

Here is an excerpt from my **params.yaml**:

```yaml
hb:
  blog:
    full_width: false # when true, the blog layout takes full width.
    sidebar:
      profile:
        # title: Profile title other than site title.
        # description: Profile description other than site description.
        # socials:
      posts:
        recent_count: 5 # the number of recent posts.
        featured_count: 5 # the number of featured posts.
        # style: pills
      taxonomies:
        count: true # whether to show the number of posts associated to the item.
        limit: 10 # the maximum number of the item.
        style: underline
    paginate: 12 # paginate.
    post_thumbnail_placeholder: "" # the text of thumbnail placeholder, default to site title.
    post_thumbnail: true # whether to show the thumbnails.
    post_thumbnail_default: images/thumbnail.jpg
    post_date_format: :date_long # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      # taxonomies: false # remove the taxonomies stat from the homepage.
      featured_posts: 5 # the number of the featured posts.
      main_sections: # leave it empty to include all regular pages.
        - docs
        - blog
        - news
```

**go.mod**:

```
github.com/hbstack/blog v0.22.1 // indirect
github.com/hbstack/blog/modules/featured-image v0.2.21 // indirect
```

hugo console log:

```
Start building sites … 
hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended linux/amd64 BuildDate=2023-09-24T15:20:17Z

WARN  image not found: /mysite/images/thumbnail.jpg?height=360px

                   | PT-BR  
-------------------+--------
  Pages            |   141  
  Paginator pages  |     1  
  Non-page files   |    28  
  Static files     |     0  
  Processed images |    73  
  Aliases          |    62  
  Sitemaps         |     2  
  Cleaned          |     0  

Built in 3105 ms
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
```
